//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vontobel.Middleware.IBT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vontobel.Middleware.IBT.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:foo=&quot;http://www.foo.org/&quot; xmlns:bar=&quot;http://www.bar.org&quot;&gt;
        ///&lt;xsl:param name=&quot;PartnerName&quot;/&gt;
        ///&lt;xsl:param name=&quot;ISIN&quot;/&gt;
        ///&lt;xsl:template match=&quot;/&quot;&gt;
        ///  &lt;html&gt;
        ///  &lt;body&gt;
        ///	&lt;h2 style=&quot;color: #5e9ca0;&quot;&gt;Dear &lt;xsl:value-of select=&quot;$PartnerName&quot;/&gt;,&lt;/h2&gt;
        ///	&lt;h2 style=&quot;color: #2e6c80;&quot;&gt;A new product has been published by Vontobel!&lt;/h2&gt;
        ///	&lt;table class=&quot;editorDemoTable&quot;&gt;
        ///	&lt;tbody&gt;
        ///	&lt;tr&gt;
        ///	&lt;td&gt;&lt;b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailTemplate {
            get {
                return ResourceManager.GetString("EmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:foo=&quot;http://www.foo.org/&quot; xmlns:bar=&quot;http://www.bar.org&quot;&gt;
        ///&lt;xsl:param name=&quot;DateTime&quot;/&gt;
        ///&lt;xsl:param name=&quot;ISIN&quot;/&gt;
        ///&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;InstrumentNotification&gt;
        ///		&lt;Timespan&gt;&lt;xsl:value-of select=&quot;$DateTime&quot;/&gt;&lt;/Timespan&gt;
        ///		&lt;ISIN&gt;&lt;xsl:value-of select=&quot;$ISIN&quot;/&gt;&lt;/ISIN&gt;
        ///	&lt;/InstrumentNotification&gt;
        ///&lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        internal static string XmlTemplate {
            get {
                return ResourceManager.GetString("XmlTemplate", resourceCulture);
            }
        }
    }
}
