//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vontobel.Middleware.IBT.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.PartnerSubscriptions = new HashSet<PartnerSubscription>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<PartnerSubscription> PartnerSubscriptions { get; set; }
    }
}
