//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vontobel.Middleware.IBT.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageContent
    {
        public string MessageId { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
