//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vontobel.Middleware.IBT.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.MessageParameters = new HashSet<MessageParameter>();
            this.SubscriptionMessageLogs = new HashSet<SubscriptionMessageLog>();
        }
    
        public string Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Picked { get; set; }
    
        public virtual MessageContent MessageContent { get; set; }
        public virtual ICollection<MessageParameter> MessageParameters { get; set; }
        public virtual ICollection<SubscriptionMessageLog> SubscriptionMessageLogs { get; set; }
    }
}
