//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vontobel.Middleware.IBT.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerSubscription
    {
        public PartnerSubscription()
        {
            this.SubscriptionMessageLogs = new HashSet<SubscriptionMessageLog>();
            this.PartnerSubscriptionParameters = new HashSet<PartnerSubscriptionParameter>();
        }
    
        public string Id { get; set; }
        public string PartnerId { get; set; }
        public string EventId { get; set; }
        public string MessageProtocolId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual MessageProtocol MessageProtocol { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual ICollection<SubscriptionMessageLog> SubscriptionMessageLogs { get; set; }
        public virtual ICollection<PartnerSubscriptionParameter> PartnerSubscriptionParameters { get; set; }
    }
}
