//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vontobel.Middleware.IBT.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VontobelDBConnection : DbContext
    {
        public VontobelDBConnection()
            : base("name=VontobelDBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Event> Events { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MessageContent> MessageContents { get; set; }
        public DbSet<MessageParameter> MessageParameters { get; set; }
        public DbSet<MessageProtocol> MessageProtocols { get; set; }
        public DbSet<Partner> Partners { get; set; }
        public DbSet<PartnerSubscription> PartnerSubscriptions { get; set; }
        public DbSet<SubscriptionMessageLog> SubscriptionMessageLogs { get; set; }
        public DbSet<PartnerSubscriptionParameter> PartnerSubscriptionParameters { get; set; }
    }
}
